### ISSUE TITLE
Handle multiple news entries per issue/type pair

### ISSUE THREAD

**Issue by gforcada** [collective/zestreleaser.towncrier#14]
Since towncrier 19.2.0 one can create more than one snippet per issue/type pair, to do so, one must suffix the entries with a counter, i.e. 
- ``123.feature``
- ``123.feature.1``
- ``123.feature.2``

Since #13 has been merged, the check there to ensure suffixes are correct would trip on these counters.

**Comment by mauritsvanrees** [comment]
I can work on this now. Or are you already coding? :-)

**Comment by gforcada** [comment]
No, I leave it to you :wink:
